/**
 * plugin-memory 构建脚本：
 * 1. tsc —— 产出 lib/types/**（host 与 client 的 .d.ts，rootDir=src）
 * 2. tsup —— host 入口 src/index.ts → lib/index.js（esm，外部化 @deepseek-ai/*）
 * 3. esbuild —— client 入口 src/client/index.ts → closure-factory 产物 lib/client.js
 *    （window.__ModuleLoader__.load({ id, factory })；外部化平台模块表 PLATFORM_MODULES）
 */
import { execFileSync } from 'node:child_process'
import { mkdirSync, rmSync, writeFileSync, readFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { build as esbuild } from 'esbuild'
import { build as tsup } from 'tsup'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
const ID = pkg.name

// 浏览器端共享平台模块（与 dsh web 的 PLATFORM_MODULES 一致）。
const PLATFORM_MODULES = [
  'react', 'react/jsx-runtime', 'react-dom', 'react-dom/client', '@deepseek-ai/cordis',
  '@deepseek-ai/dsh-client-store',
  '@deepseek-ai/dsh-client-ui-slots',
  '@deepseek-ai/dsh-client-ui-primitives',
]

// 每次构建先清空 lib：已删除的源码（如 render.ts / template-default.ts）不得留旧产物。
rmSync(join(root, 'lib'), { recursive: true, force: true })

const INJECT_MODULES = pkg.dsh?.client?.inject ?? []
const CLIENT_EXTERNAL = [
  ...PLATFORM_MODULES,
  ...INJECT_MODULES.flatMap((m) => [m, `${m}/client`]),
]

/** 1. 类型声明（tsc emitDeclarationOnly）。 */
function emitTypes() {
  execFileSync('npx', ['tsc', '-p', join(root, 'tsconfig.json')], {
    cwd: root,
    stdio: 'inherit',
    shell: process.platform === 'win32',
  })
}

/** 2. host 入口 → lib/index.js。 */
async function buildHost() {
  await tsup({
    entry: { index: join(root, 'src/index.ts') },
    outDir: join(root, 'lib'),
    format: ['esm'],
    platform: 'node',
    target: 'es2022',
    clean: false,
    dts: false,
    sourcemap: false,
    external: [/^@deepseek-ai\//],
  })
}

/** 3. client 入口 → lib/client.js（closure-factory 产物）。 */
async function buildClient() {
  const result = await esbuild({
    entryPoints: [join(root, 'src/client/index.ts')],
    bundle: true,
    format: 'cjs',
    platform: 'browser',
    target: 'es2022',
    external: CLIENT_EXTERNAL,
    loader: { '.css': 'text', '.png': 'dataurl', '.webp': 'dataurl' },
    jsx: 'automatic',
    define: { 'process.env.NODE_ENV': '"production"' },
    minify: true,
    write: false,
  })
  const body = result.outputFiles[0].text
  const artifact = [
    '/* generated by scripts/build.mjs — do not edit */',
    'window.__ModuleLoader__.load({',
    `  id: ${JSON.stringify(ID)},`,
    '  factory: (require) => {',
    '    var module = { exports: {} };',
    '    var exports = module.exports;',
    body,
    '    return module.exports;',
    '  },',
    '});',
    '',
  ].join('\n')
  mkdirSync(join(root, 'lib'), { recursive: true })
  writeFileSync(join(root, 'lib/client.js'), artifact, 'utf8')
}

await emitTypes()
await buildHost()
await buildClient()
console.log(`[plugin-memory] built lib/index.js + lib/client.js + lib/types for ${ID}`)